event/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('sort/', views.SortedPosts.as_view(), name='sorted_posts.html'),
    path('addpost/', views.AddEvent.as_view(), name='add_post'),
    path('myposts/', views.MyEvents.as_view(), name='my_posts'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('posts/<slug:slug>/update',
         views.UpdateEvent.as_view(), name='update_post'),
    path('posts/<slug:slug>/delete',
         views.DeleteEvent.as_view(), name='delete_post'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls'), name='event_urls'),
    path('accounts/', include('allauth.urls')),
]

event/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django_extensions.db.fields import AutoSlugField
from django.utils import timezone
from django.urls import reverse


EVENT_TYPES = ((0, 'Music'), (1, 'Art'), (2, 'Other'))
STATUS = ((0, 'Draft'), (1, 'Published'))
EVENT_STATUS = [
    ('initial', 'Initial'),
    ('passed', 'Passed'),
    ('cancelled', 'Cancelled'),
]
AREA_CHOICES = [
    ('jamtland', 'Jämtland'),
    ('ostersund', 'Östersund'),
    ('krokom', 'Krokom'),
    ('berg', 'Berg'),
    ('are', 'Åre'),
    ('bracke', 'Bräcke'),
    ('harjedalen', 'Härjedalen'),
    ('ragunda', 'Ragunda'),
    ('stromsund', 'Strömsund'),
]


REVIEW_TYPES = ((1, '1 Star'),
                (2, '2 Stars'),
                (3, '3 Stars'),
                (4, '4 Stars'),
                (5, '5 Stars'),
                )

# post model for ading events as posts
# initial code based on the django blog walkthrough project and adapted to
# fit this sites functions. Timezone import info from:
# slug from
# https://django-extensions.readthedocs.io/en/latest/field_extensions.html#
# https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/


class Post(models.Model):
    title = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    event_start = models.DateTimeField(default=timezone.now)
    slug = AutoSlugField(
        populate_from=['title', 'event_start'], max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="event_posts")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    about = models.TextField()
    event_image = CloudinaryField('image', default='placeholder')
    link = models.URLField(blank=True)
    area = models.CharField(max_length=100, choices=AREA_CHOICES,
                            default='jamtland')
    locale = models.CharField(max_length=100)
    event_type = models.IntegerField(choices=EVENT_TYPES, default=0)
    status = models.IntegerField(choices=STATUS, default=1)
    event_status = models.CharField(
        max_length=10, choices=EVENT_STATUS, default='initial')

    def is_event_cancelled(self):
        return self.event_status == 'cancelled'

    def is_event_passed(self):
        return self.event_start < timezone.now()

    def update_event_status(self):
        if self.is_event_passed():
            self.event_status = 'passed'
        elif self.is_event_cancelled():
            self.event_status = 'cancelled'
        else:
            self.event_status = 'initial'

        self.save()

    class Meta:
        ordering = ['-created_on']

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

event/forms.py
from .models import Post
from django import forms


class EventForm(forms.ModelForm):
    '''create event form'''

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = [
            'title',
            'artist',
            'event_start',
            'about',
            'event_image',
            'link',
            'area',
            'locale',
            'event_type',
            'event_status',
        ]

event/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic, View
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Post
from .forms import EventForm


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(
        status=1, event_status='initial').order_by('event_start')
    template_name = 'index.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        for post in context['object_list']:
            post.update_event_status()

        context['last_event_added'] = Post.objects.filter(
            status=1).order_by('-created_on').first()
        context['last_event_start'] = Post.objects.filter(
            event_status='initial').order_by('event_start').first()
        return context

# initial code info for the "get_queryset" from
# https://stackoverflow.com/questions/6262629/sorting-through-request-get-in-django
# get_context_data info from_
# https://stackoverflow.com/a/36950584


class SortedPosts(generic.ListView):
    model = Post
    template_name = 'sorted_posts.html'
    paginate_by = 6

    def get_queryset(self):
        sort_by = self.request.GET.get('sort_by', '-created_on')

        if sort_by not in ['event_start',
                           '-event_start',
                           'created_on',
                           '-created_on']:
            sort_by = '-created_on'

        queryset = Post.objects.filter(
            status=1, event_status__in=['initial', 'cancelled'])

        if sort_by == 'event_start':
            queryset = queryset.order_by('event_start')
        elif sort_by == '-event_start':
            queryset = queryset.order_by('-event_start')
        elif sort_by == 'created_on':
            queryset = queryset.order_by('created_on')
        elif sort_by == '-created_on':
            queryset = queryset.order_by('-created_on')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        for post in context['object_list']:
            post.update_event_status()

        context['sort_by'] = self.request.GET.get('sort_by', '-created_on')
        context['post.event_start'] = Post.objects.filter(
            status=1, event_status__in=['initial', 'cancelled']).order_by(
                '-event_start').first()
        return context


class PostDetail(View):
    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)

        return render(
            request,
            'post_detail.html',
            {
                'post': post,
            },
        )


class AddEvent(generic.CreateView):
    form_class = EventForm
    template_name = 'add_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'Event Suceessfully Submitted!')
        return super().form_valid(form)


class MyEvents(generic.ListView):
    model = Post
    template_name = 'my_posts.html'
    paginate_by = 3

    def get_queryset(self):

        return Post.objects.filter(author=self.request.user)


class UpdateEvent(generic.UpdateView):
    model = Post
    form_class = EventForm
    template_name = 'update_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'Event suceessfully Updated!')
        return super().form_valid(form)


class DeleteEvent(generic.DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('my_posts')

    def dispatch(self, request, *args, **kwargs):
        post = self.get_object()
        if not request.user.is_authenticated or post.author != request.user:
            messages.error(
                request, "You do not have permission to delete this post.")
            return redirect('my_posts')
        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Post deleted successfully.")
        return super().delete(request, *args, **kwargs)

templates/add_post.html
{% extends "base.html" %}

{% block title %}Add Event{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}

<div class="container">
    <h1 class="padding">Add Event</h1>

    <div class="row justify-content-center ">
        {% if user.is_authenticated %}
        {% load cloudinary %}
        <div class="col-11 col-md-8 col-lg-6 mt-3">
            <form method="post" class="mb-5" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-success">Submit</button>
                <a class="btn btn-warning" href="">Cancel</a>
            </form>
        </div>
        {% endif %}
    </div>
</div>

{%endblock%}

templates/delete_post.html
{% extends "base.html" %}


{% block title %}Delete Post{% endblock %}

{% block content %}
<div class="container col-md-6">
    <div class="card margin">
        <h1>Delete Post</h1>

        <p>Are you sure you want to delete this event?</p>

        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn btn-warning" href="{%  url 'post_detail' post.slug  %}">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Events in Jämtland{% endblock title %}

{% block content %}


<h1 class="text-center padding">Find out what happens near you!</h1>
<!-- check if there are post and displays message if not -->
{% if object_list %}
<div class="container padding">
    <div class="row justify-content-evenly">

        <div class="col-md-5">
            <div class="row text-center">
                <h2>Next Upcoming Event</h2>
                <div class="col">
                    <a href="{% url 'sorted_posts.html' %}?sort_by=event_start" class="btn btn-primary" role="button">
                        View All Upcoming
                    </a>
                </div>
            </div>
            <div class="card">
                <a href="{% url 'post_detail' last_event_start.slug %}">
                    {% if 'placeholder' in last_event_start.event_image.url %}
                    <div>
                        <img src="https://i.imgur.com/wA1pmla.jpg" class="card-img" alt="{{ last_event_start.title }}">
                    </div>
                    {% else %}
                    <div>
                        <img src="{{ last_event_start.event_image.url }}" class="card-img"
                            alt="{{ last_event_start.title }}">
                    </div>
                    {% endif %}
                </a>
                <div class="card-body text-center">
                    <h5 class="card-title"><a class="link-header" href="{% url 'post_detail' last_event_start.slug %}">
                            {{last_event_start.title}}</h5></a>
                    <div>
                        {% if last_event_start.about|length > 225 %}
                        <p class="card-text">{{ last_event_start.about|truncatechars:225 }}<a
                                href="{% url 'post_detail' last_event_start.slug %}">Read More</a></p>
                        {% else %}
                        <p class="card-text">{{ last_event_start.about }}</p>
                        {% endif %}
                    </div>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item">
                        <i class="fa-regular fa-calendar-days"> </i> {{ last_event_start.event_start|date:'D, d M Y' }}
                        |
                        <i class="fa-regular fa-clock"> </i> {{last_event_start.event_start|time:'H:i' }}
                    </li>
                    <li class="list-group-item">
                        <i class="fa-solid fa-map-location-dot"> </i> {{ last_event_start.get_area_display }} |
                        {{ last_event_start.locale}}</h5>
                    </li>
                    <li class="list-group-item">
                        <p class="card-text"><small class="text-muted">Added: {{ last_event_start.created_on }}
                                {% if last_event_start.created_on > last_event_start.updated_on %}
                                <br>Updated: {{last_event_start.updated_on }}
                                {% endif %}
                            </small></p>
                    </li>
                </ul>
                <div class="card-body text-center">
                    <a href="{% url 'post_detail' last_event_start.slug %}" class="card-link">Go to Event</a>
                    {% if last_event_start.link != '' %}
                    <a href="{{ last_event_start.link }}" target="_blank" class="card-link">Official Link</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="row text-center">
                <h2>Latest added Event</h2>
                <div class="col">
                    <a href="{% url 'sorted_posts.html' %}?sort_by=-created_on" class="btn btn-primary" role="button">
                        View All Latest
                    </a>
                </div>
            </div>
            <div class="card">
                <a href="{% url 'post_detail' last_event_added.slug %}">
                    {% if 'placeholder' in last_event_added.event_image.url %}
                    <div>
                        <img src="https://i.imgur.com/wA1pmla.jpg" class="card-img" alt="{{ last_event_added.title }}">
                    </div>
                    {% else %}
                    <div>
                        <img src="{{ last_event_added.event_image.url }}" class="card-img"
                            alt="{{ last_event_added.title }}">
                    </div>
                    {% endif %}
                </a>
                <div class="card-body text-center">
                    <h5 class="card-title"><a class="link-header" href="{% url 'post_detail' last_event_added.slug %}">
                            {{last_event_added.title}}</h5></a>
                    <div>
                        <!-- cut off text and link to full text -->
                        {% if last_event_added.about|length > 225 %}
                        <p class="card-text">{{ last_event_added.about|truncatechars:225 }}<a
                                href="{% url 'post_detail' last_event_added.slug %}">Read More</a></p>
                        {% else %}
                        <p class="card-text">{{ last_event_added.about }}</p>
                        {% endif %}
                    </div>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item">
                        <i class="fa-regular fa-calendar-days"> </i> {{ last_event_added.event_start|date:'D, d M Y' }}
                        |
                        <i class="fa-regular fa-clock"> </i> {{last_event_added.event_start|time:'H:i' }}
                    </li>
                    <li class="list-group-item">
                        <i class="fa-solid fa-map-location-dot"> </i> {{ last_event_added.get_area_display }} |
                        {{ last_event_added.locale}}</h5>
                    </li>
                    <li class="list-group-item">
                        <p class="card-text"><small class="text-muted">Added: {{ last_event_added.created_on }}
                                {% if last_event_added.created_on > last_event_added.updated_on %}
                                <br>Updated: {{last_event_added.updated_on }}
                                {% endif %}
                            </small></p>
                    </li>
                </ul>
                <div class="card-body text-center">
                    <a href="{% url 'post_detail' last_event_added.slug %}" class="card-link">Go to Event</a>
                    {% if last_event_added.link != '' %}
                    <a href="{{ last_event_added.link }}" target="_blank" class="card-link">Official Link</a>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
</div>
<!-- no event available message -->
{% else %}
<div class="container padding">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">No events available :(</h5>
                <p class="card-text">There are currently no events to display.
                    {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'add_post' %}" aria-label="Add Event link">Add
                        Event!</a>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'account_login' %}" aria-label="Add Event link">
                        Log In</a>
                    and add event!
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endif %}


{% endblock content %}

templates/my_posts.html
{% extends "base.html" %}
{% block title %}My Events{% endblock %}
{% block content %}

{% if object_list %}
<div class="container mt-5">
    <h2 class="padding">My Events</h2>
    <div class="row">
        {% for post in post_list %}
        <div class="col-md-12 mb-4">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        {% if post.is_event_cancelled %}
                        <div class="status status-cancelled">
                            <h3>Event Cancelled</h3>
                        </div>
                        {% elif post.is_event_passed %}
                        <div class="status status-passed">
                            <h3>Event Passed</h3>
                        </div>
                        {% else %}
                        {% endif %}
                        <a href="{% url 'post_detail' post.slug %}">
                            {% if 'placeholder' in post.event_image.url %}
                            <img src="https://i.imgur.com/wA1pmla.jpg" class="card-img" alt="{{ post.title }}">
                            {% else %}
                            <img src="{{ post.event_image.url }}" class="card-img" alt="{{ post.title }}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><a class="link-header"
                                    href="{% url 'post_detail' post.slug %}">{{post.title }}</h5></a>
                            <div>
                                {% if post.about|length > 225 %}
                                <p class="card-text">{{ post.about|truncatechars:225 }}<a
                                        href="{% url 'post_detail' post.slug %}">Read More</a></p>
                                {% else %}
                                <p class="card-text">{{ post.about }}</p>
                                {% endif %}
                            </div>
                            <h5><i class="fa-solid fa-map-location-dot"> </i> {{ post.get_area_display }} |
                                {{ post.locale}}</h5>
                            <h5><i class="fa-regular fa-calendar-days"> </i> {{ post.event_start|date:'D, d M Y' }} |
                                <i class="fa-regular fa-clock"> </i> {{post.event_start|time:'H:i' }}
                            </h5>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Event Page</a>
                            {% if last_event_start.link != '' %}
                            <a href="{{ post.link }}" class="btn btn-primary" target="_blank">Official Link</a>
                            {% endif %}
                            <p class="card-text"><small class="text-muted">Added: {{ post.created_on }}
                                    {% if post.created_on > post.updated_on %}
                                    <br>Updated: {{post.updated_on }}
                                    {% endif %}
                                </small></p>
                            {% if user.is_authenticated and post.author == user %}
                            <div class="col">
                                <a class="btn btn-warning" role="button" aria-label="Update post link"
                                    href="{% url 'update_post' post.slug %}">Update</a>
                                <a class="btn btn-danger" role="button" aria-label="Delete post link"
                                    href="{% url 'delete_post' post.slug %}">Delete</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% else %}
<div class="container padding">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">No events available :(</h5>
                <p class="card-text">There are currently no events to display.
                    {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'add_post' %}" aria-label="Add Event link">Add
                        Event!</a>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'account_login' %}" aria-label="Add Event link">
                        Log In</a>
                    and add event!
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endif %}


<div class="container-fluid">
    <div class="row">
        {% if is_paginated %}
        <nav aria-label="Page Navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREVIOUS</a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">NEXT &raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- initial card code from https://getbootstrap.com/docs/4.3/components/card/ -->
<div class="container-fluid">
    <div class="card margin">
        <div class="row no-gutters">
            <div class="col-md-4">
                {% if 'placeholder' in post.event_image.url %}
                <div>
                    <img class="card-img-top" src="https://i.imgur.com/wA1pmla.jpg" alt="placeholder image">
                </div>
                {% else %}
                <div class="ratio-container">
                    <img class="card-img-top" src="{{ post.event_image.url }}" alt="user uploaded image">
                </div>
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title">{{ post.title }}</h4>
                    <h6 class="card-title">{{ post.event_date }} {{ post.event_time }}</h6>
                    <h5><i class="fa-solid fa-map-location-dot"> </i> {{ post.get_area_display }} |
                        {{ post.locale}}</h5>
                    <h5><i class="fa-regular fa-calendar-days"> </i> {{ post.event_start|date:'D, d M Y' }} |
                        <i class="fa-regular fa-clock"> </i> {{post.event_start|time:'H:i' }}
                    </h5>
                    <p class="card-text">{{ post.about }}</p>
                    {% if last_event_start.link != '' %}
                    <a href="{{ post.link }}" class="btn btn-primary" target="_blank">Official Link</a>
                    {% endif %}
                    <p class="card-text"><small class="text-muted">Added: {{ post.created_on }}
                            {% if post.created_on > post.updated_on %}
                            <br>Updated: {{post.updated_on }}
                            {% endif %}
                        </small></p>
                </div>
            </div>
            {% if user.is_authenticated and post.author == user %}
            <div class="col text-center">
                <a class="btn btn-warning" role="button" aria-label="Update post link"
                    href="{% url 'update_post' post.slug %}">Update</a>
                <a class="btn btn-danger" role="button" aria-label="Delete post link"
                    href="{% url 'delete_post' post.slug %}">Delete</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/sorted_posts.html
{% extends "base.html" %}

{% block title %}Sorted Events{% endblock title %}

{% block content %}

<div class="text-center">
    <h1 class="padding">All Events</h1>
    <h4>Sort Events</h4>
    <a href="{% url 'sorted_posts.html' %}?sort_by=event_start">Upcoming Events (Next)</a> |
    <a href="{% url 'sorted_posts.html' %}?sort_by=-event_start">Upcoming Events (Last)</a> |
    <a href="{% url 'sorted_posts.html' %}?sort_by=created_on">Date Added (Oldest)</a> |
    <a href="{% url 'sorted_posts.html' %}?sort_by=-created_on">Date Added (Latest)</a>
</div>
<!-- check if there are post and displays message if not -->
{% if object_list %}
<div class="container mt-5">
    <div class="row">
        {% for post in post_list %}
        <div class="col-md-12 mb-4">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        {% if post.is_event_cancelled %}
                        <div class="status status-cancelled">
                            <h3>Event Cancelled</h3>
                        </div>
                        {% elif post.is_event_passed %}
                        <div class="status status-passed">
                            <h3>Event Passed</h3>
                        </div>
                        {% else %}
                        {% endif %}
                        <a href="{% url 'post_detail' post.slug %}">
                            {% if 'placeholder' in post.event_image.url %}
                            <img src="https://i.imgur.com/wA1pmla.jpg" class="card-img" alt="{{ post.title }}">
                            {% else %}
                            <img src="{{ post.event_image.url }}" class="card-img" alt="{{ post.title }}">
                            {% endif %}
                        </a>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><a class="link-header"
                                    href="{% url 'post_detail' post.slug %}">{{post.title }}</h5></a>
                            <div>
                                <!-- cut off text and link to full text -->
                                {% if post.about|length > 225 %}
                                <p class="card-text">{{ post.about|truncatechars:225 }}<a
                                        href="{% url 'post_detail' post.slug %}">Read More</a></p>
                                {% else %}
                                <p class="card-text">{{ post.about }}</p>
                                {% endif %}
                            </div>
                            <h5><i class="fa-solid fa-map-location-dot"> </i> {{ post.get_area_display }} |
                                {{ post.locale}}</h5>
                            <h5><i class="fa-regular fa-calendar-days"> </i> {{ post.event_start|date:'D, d M Y' }} |
                                <i class="fa-regular fa-clock"> </i> {{post.event_start|time:'H:i' }}
                            </h5>
                            <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Event Page</a>
                            {% if last_event_start.link != '' %}
                            <a href="{{ post.link }}" class="btn btn-primary" target="_blank">Official Link</a>
                            {% endif %}
                            <p class="card-text"><small class="text-muted">Added: {{ post.created_on }}
                                    {% if post.created_on > post.updated_on %}
                                    <br>Updated: {{post.updated_on }}
                                    {% endif %}
                                </small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- no event available message -->
{% else %}
<div class="container padding">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">No events available :(</h5>
                <p class="card-text">There are currently no events to display.
                    {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'add_post' %}" aria-label="Add Event link">Add
                        Event!</a>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'account_login' %}" aria-label="Add Event link">
                        Log In</a>
                    and add event!
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endif %}


<div class="container-fluid">
    <div class="row">
        {% if is_paginated %}
        <nav aria-label="Page Navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li>
                    <a href="?sort_by={{ sort_by }}&page={{ page_obj.previous_page_number }}" class="page-link">&laquo;
                        PREVIOUS</a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li>
                    <a href="?sort_by={{ sort_by }}&page={{ page_obj.next_page_number }}" class="page-link">NEXT
                        &raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock content %}